NANOSECONDS = 1
MICROSECONDS = 1000 * NANOSECONDS
MILLISECONDS = 1000 * MICROSECONDS
SECONDS = 1000 * MILLISECONDS

MINE_RATE = 4 * SECONDS

INITIAL_BALANCE = 1000

MINING_REWARD = 50
MINING_REWARD_INPUT = { "address": "*--suzuki-mining-reward--*"}

FRONTEND_ADDRESS="http://localhost:3000"