class TransactionPool:
    """
    Collects transactions that have been broadcast across network. 
        -  Manages state of Tx according to respective ID.
        -  Pool collates prospective data (Tx) for new blocks.
    """
    def __init__(self):
        self.transaction_map = {}
    
    def set_transaction(self, transaction):
        """
        Set a transaction in the transaction pool.
        """
        self.transaction_map[transaction.id] = transaction

    def existing_transaction(self, address):
        """
        Find a transaction generated by a given address in the transaction pool
        """
        for transaction in self.transaction_map.values():
            if (transaction.input["address"] == address):
                return transaction