const API_BASE_URI = "http://localhost:5000"
const NANOSECONDS_PY = 1;
const MICROSECONDS_PY = 1000 * NANOSECONDS_PY
const MILLISECONDS_PY = 1000 * MICROSECONDS_PY

module.exports = {
    ROOT_PATH: API_BASE_URI,
    MICROSECONDS_PY: MICROSECONDS_PY
  };